const customFoods = [
  // ── Rice & Bread ─────────────────────────────────────────────────────────────
  {
    id: "custom_dal_bhat",
    name: "Dal Bhat (1 plate)",
    calories: 450,
    protein: 15,
    carbs: 78,
    fat: 5,
    source: "custom",
    per: "1 serving",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/dal_bhat.jpg",
  },
  {
    id: "custom_dhido",
    name: "Dhido (1 serving)",
    calories: 320,
    protein: 8,
    carbs: 65,
    fat: 3,
    source: "custom",
    per: "1 serving",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/dhiido.jpeg",
  },
  {
    id: "custom_roti",
    name: "Roti (1 piece)",
    calories: 120,
    protein: 3,
    carbs: 22,
    fat: 2,
    source: "custom",
    per: "1 piece",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/roti.webp",
  },
  {
    id: "custom_sel_roti",
    name: "Sel Roti (1 piece)",
    calories: 180,
    protein: 3,
    carbs: 28,
    fat: 6,
    source: "custom",
    per: "1 piece",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/sel_roti.webp",
  },
  {
    id: "custom_chiura",
    name: "Chiura / Beaten Rice (100g)",
    calories: 350,
    protein: 6,
    carbs: 77,
    fat: 1,
    source: "custom",
    per: "100g",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/chuira.webp",
  },

  // ── Momo ─────────────────────────────────────────────────────────────────────
  {
    id: "custom_chicken_momo",
    name: "Chicken Momo Steamed (6 pieces)",
    calories: 280,
    protein: 20,
    carbs: 28,
    fat: 8,
    source: "custom",
    per: "6 pieces",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/momo.jpg",
  },
  {
    id: "custom_buff_momo",
    name: "Buff Momo Steamed (6 pieces)",
    calories: 260,
    protein: 18,
    carbs: 28,
    fat: 7,
    source: "custom",
    per: "6 pieces",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/buff_momo.jpg",
  },
  {
    id: "custom_veg_momo",
    name: "Veg Momo Steamed (6 pieces)",
    calories: 220,
    protein: 8,
    carbs: 32,
    fat: 6,
    source: "custom",
    per: "6 pieces",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/veg_momo.webp",
  },
  {
    id: "custom_fried_momo",
    name: "Fried Momo (6 pieces)",
    calories: 360,
    protein: 18,
    carbs: 30,
    fat: 16,
    source: "custom",
    per: "6 pieces",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/fried.avif",
  },
  {
    id: "custom_jhol_momo",
    name: "Jhol Momo (6 pieces with soup)",
    calories: 320,
    protein: 20,
    carbs: 34,
    fat: 10,
    source: "custom",
    per: "1 bowl",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/jhol_momo.jpg",
  },

  // ── Curries & Sides ──────────────────────────────────────────────────────────
  {
    id: "custom_chicken_curry",
    name: "Chicken Curry (1 serving)",
    calories: 320,
    protein: 28,
    carbs: 8,
    fat: 18,
    source: "custom",
    per: "1 serving",
    imageUri: null,
  },
  {
    id: "custom_mutton_curry",
    name: "Mutton Curry (1 serving)",
    calories: 380,
    protein: 30,
    carbs: 6,
    fat: 24,
    source: "custom",
    per: "1 serving",
    imageUri: null,
  },
  {
    id: "custom_aloo_tama",
    name: "Aloo Tama (1 serving)",
    calories: 180,
    protein: 5,
    carbs: 28,
    fat: 5,
    source: "custom",
    per: "1 serving",
    imageUri: null,
  },
  {
    id: "custom_gundruk_jhol",
    name: "Gundruk ko Jhol (1 bowl)",
    calories: 60,
    protein: 3,
    carbs: 8,
    fat: 2,
    source: "custom",
    per: "1 bowl",
    imageUri: null,
  },
  {
    id: "custom_saag",
    name: "Saag (1 serving)",
    calories: 80,
    protein: 4,
    carbs: 8,
    fat: 4,
    source: "custom",
    per: "1 serving",
    imageUri: null,
  },
  {
    id: "custom_kwati",
    name: "Kwati (mixed bean soup, 1 bowl)",
    calories: 220,
    protein: 14,
    carbs: 32,
    fat: 4,
    source: "custom",
    per: "1 bowl",
    imageUri: null,
  },
  {
    id: "custom_tomato_achar",
    name: "Tomato Achar (2 tbsp)",
    calories: 40,
    protein: 1,
    carbs: 6,
    fat: 1,
    source: "custom",
    per: "2 tbsp",
    imageUri: null,
  },

  // ── Snacks & Street Food ─────────────────────────────────────────────────────
  {
    id: "custom_chatamari",
    name: "Chatamari (1 piece)",
    calories: 160,
    protein: 5,
    carbs: 28,
    fat: 3,
    source: "custom",
    per: "1 piece",
    imageUri: null,
  },
  {
    id: "custom_bara",
    name: "Bara (1 piece)",
    calories: 140,
    protein: 6,
    carbs: 18,
    fat: 4,
    source: "custom",
    per: "1 piece",
    imageUri: null,
  },
  {
    id: "custom_yomari",
    name: "Yomari (1 piece)",
    calories: 150,
    protein: 3,
    carbs: 28,
    fat: 3,
    source: "custom",
    per: "1 piece",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/yomari.jpg",
  },
  {
    id: "custom_samay_baji",
    name: "Samay Baji (1 plate)",
    calories: 520,
    protein: 22,
    carbs: 68,
    fat: 14,
    source: "custom",
    per: "1 plate",
    imageUri: null,
  },
  {
    id: "custom_sukuti",
    name: "Sukuti / Dried Meat (100g)",
    calories: 290,
    protein: 42,
    carbs: 2,
    fat: 12,
    source: "custom",
    per: "100g",
    imageUri: null,
  },

  // ── Noodles & Soup ────────────────────────────────────────────────────────────
  {
    id: "custom_thukpa",
    name: "Thukpa (1 bowl)",
    calories: 380,
    protein: 18,
    carbs: 52,
    fat: 8,
    source: "custom",
    per: "1 bowl",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/thukpa.jpg",
  },
  {
    id: "custom_wai_wai",
    name: "Wai Wai Noodles (1 packet dry)",
    calories: 420,
    protein: 10,
    carbs: 58,
    fat: 16,
    source: "custom",
    per: "1 packet",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/wai_wai.jpg",
  },

  // ── Desserts & Drinks ─────────────────────────────────────────────────────────
  {
    id: "custom_kheer",
    name: "Kheer (1 bowl)",
    calories: 280,
    protein: 8,
    carbs: 42,
    fat: 9,
    source: "custom",
    per: "1 bowl",
    imageUri:
      "https://tysuyhaqmgldtusocftj.supabase.co/storage/v1/object/public/meal-images/custom_foods/kheer.jpg",
  },
  {
    id: "custom_juju_dhau",
    name: "Juju Dhau / Yogurt (100g)",
    calories: 100,
    protein: 4,
    carbs: 12,
    fat: 4,
    source: "custom",
    per: "100g",
    imageUri: null,
  },
  {
    id: "custom_chiya",
    name: "Chiya / Milk Tea (1 cup)",
    calories: 60,
    protein: 2,
    carbs: 10,
    fat: 2,
    source: "custom",
    per: "1 cup",
    imageUri: null,
  },
  {
    id: "custom_lassi",
    name: "Lassi (1 glass)",
    calories: 180,
    protein: 6,
    carbs: 28,
    fat: 5,
    source: "custom",
    per: "1 glass",
    imageUri: null,
  },
];

export default customFoods;
